replicaCount: 3

image:
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.ap-southeast-1.amazonaws.com/sample-app
  tag: "0.1.0"
  pullPolicy: IfNotPresent

env:
  appName: sample-app
  appEnv: prod
  appVersion: "0.1.0"

service:
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: 150m
    memory: 192Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
  hosts:
    - host: sample-app-prod.local
      paths:
        - path: /
          pathType: Prefix
  tls: []