replicaCount: 2

image:
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.ap-southeast-1.amazonaws.com/sample-app
  tag: "0.1.0"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

env: 
  appName: sample-app
  appEnv: dev
  appVersion: "0.1.0"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

probes:
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 15
  readiness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 10

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: sample-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []