apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sample-app
  namespace: argocd
spec:
  description: Sample app project
  sourceRepos:
    - __GIT_REPO_URL__
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: prod
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: networking.k8s.io
      kind: Ingress
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
