apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-prod
  namespace: argocd
spec:
  project: sample-app
  source:
    repoURL: https://github.com/<GITHUB_OWNER>/eks-platform-infra.git
    targetRevision: main
    path: sample-app-gitops/helm/sample-app
    helm:
      valueFiles:
        - ../../envs/prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true